name: Godot CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot
        uses: barichello/godot-ci@v6
        with:
          version: 4.2.2

      - name: Import project
        run: godot --headless --import

      - name: Check for errors
        run: godot --headless --quit

      - name: Export
        run: |
          mkdir -p build
          godot --headless --export-release "Linux/X11" build/game.x86_64
